### ISSUE TITLE
Depuración modelo relacional

### ISSUE THREAD

**Issue by morenopablo16** [UNIZAR-30226-2024-01/backend#2]

**Comment by luoolmos** [comment]
![relacional_v1](https://github.com/UNIZAR-30226-2024-01/backend/assets/146450799/54558d35-c69a-4ca3-b89f-cbd4b7ef7e70)

**Comment by luoolmos** [comment]
![relacional_v1_20230403](https://github.com/UNIZAR-30226-2024-01/backend/assets/146450799/3e9143eb-9e83-4187-b335-022094363c65)
